#!/usr/bin/env bash

# MacSetup (server) — unattended maintenance
#
# On a desktop you run brew-maintenance.sh when you think of it. On a headless
# box nobody thinks of it, so this installs a LaunchAgent that runs the same
# maintenance weekly and writes a log you can check over SSH.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

for dep in "$REPO_ROOT/lib.sh" "$SCRIPT_DIR/lib-server.sh"; do
    if [[ ! -f "$dep" ]]; then
        echo "Error: missing $dep (required by this script)" >&2
        exit 1
    fi
done
# shellcheck source=../lib.sh
source "$REPO_ROOT/lib.sh"
# shellcheck source=lib-server.sh
source "$SCRIPT_DIR/lib-server.sh"

LABEL="cloud.jameskilby.macsetup.maintenance"
AGENT_DIR="$HOME/Library/LaunchAgents"
PLIST="$AGENT_DIR/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs/MacSetup"
# Generated, not checked in — it hardcodes this clone's absolute path.
RUNNER_DIR="$HOME/.local/share/macsetup"
RUNNER="$RUNNER_DIR/run-maintenance.sh"

# A small wrapper the agent invokes. launchd starts jobs with a minimal PATH
# that does not include Homebrew, so the wrapper establishes the environment
# before handing off to the shared brew-maintenance.sh.
write_runner() {
    mkdir -p "$RUNNER_DIR"

    cat > "$RUNNER" <<EOF
#!/usr/bin/env bash
# Generated by server/maintenance-setup.sh — invoked by the $LABEL LaunchAgent.
# Safe to edit; re-running maintenance-setup.sh will overwrite it.

set -uo pipefail

# launchd gives us a bare PATH — put Homebrew back on it.
if [[ -x $BREW_BIN ]]; then
    eval "\$($BREW_BIN shellenv)"
else
    echo "Homebrew not found at $BREW_BIN — nothing to maintain" >&2
    exit 1
fi

echo "===== \$(date '+%Y-%m-%d %H:%M:%S') — starting maintenance ====="
bash "$REPO_ROOT/brew-maintenance.sh" full
status=\$?
echo "===== \$(date '+%Y-%m-%d %H:%M:%S') — finished (exit \$status) ====="
exit \$status
EOF

    chmod +x "$RUNNER"
    log_success "Wrote $RUNNER"
}

write_plist() {
    mkdir -p "$AGENT_DIR" "$LOG_DIR"

    cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNNER</string>
    </array>

    <!-- Sundays at 04:00. -->
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key><integer>0</integer>
        <key>Hour</key><integer>4</integer>
        <key>Minute</key><integer>0</integer>
    </dict>

    <!-- If the machine was off at 04:00, run once it comes back. -->
    <key>RunAtLoad</key>
    <false/>

    <!-- Maintenance is background work; don't compete with real workloads. -->
    <key>Nice</key>
    <integer>10</integer>
    <key>LowPriorityIO</key>
    <true/>
    <key>ProcessType</key>
    <string>Background</string>

    <key>StandardOutPath</key>
    <string>$LOG_DIR/maintenance.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/maintenance.log</string>
</dict>
</plist>
EOF

    log_success "Wrote $PLIST"
}

load_agent() {
    local uid
    uid="$(id -u)"

    # Unload any previous version first so a re-run replaces cleanly.
    launchctl bootout "gui/$uid/$LABEL" &>/dev/null || true

    if launchctl bootstrap "gui/$uid" "$PLIST" 2>/dev/null; then
        log_success "LaunchAgent loaded"
    else
        log_warning "launchctl bootstrap failed — trying the legacy load path"
        try "Load via launchctl load" launchctl load -w "$PLIST"
    fi

    try "Enable the agent" launchctl enable "gui/$uid/$LABEL"
}

install_logrotate() {
    # newsyslog is already running on macOS; a drop-in keeps the log bounded
    # without adding another moving part.
    local conf="/etc/newsyslog.d/macsetup-maintenance.conf"
    local tmp
    tmp="$(mktemp)"

    # logfilename  owner:group  mode  count  size(KB)  when  flags
    printf '%-50s %s:%s 644 5 1024 * J\n' \
        "$LOG_DIR/maintenance.log" "$(id -un)" "$(id -gn)" > "$tmp"

    if sudo cp "$tmp" "$conf" && sudo chmod 644 "$conf" && sudo chown root:wheel "$conf"; then
        log_success "Log rotation configured ($conf)"
    else
        log_warning "Could not configure log rotation — the log will grow unbounded"
    fi
    rm -f "$tmp"
}

main() {
    require_apple_silicon
    log_header "Unattended Maintenance"

    log_info "Installs a weekly LaunchAgent (Sundays 04:00) that runs:"
    log_info "  brew update && brew upgrade && brew cleanup && brew doctor"
    log_info "Output goes to $LOG_DIR/maintenance.log"
    echo

    if ! ask "Install the weekly maintenance job?" y; then
        log_info "Skipping unattended maintenance"
        exit 0
    fi

    write_runner
    write_plist
    load_agent

    if ask "Configure log rotation (needs sudo)?" y; then
        require_sudo
        install_logrotate
    fi

    echo
    warn_if_no_autologin

    echo
    log_success "Maintenance job installed"
    log_info "Verify:   launchctl list | grep macsetup"
    log_info "Run now:  launchctl kickstart -k gui/$(id -u)/$LABEL"
    log_info "Logs:     tail -f $LOG_DIR/maintenance.log"
    log_info "Remove:   launchctl bootout gui/$(id -u)/$LABEL && rm $PLIST"
}

main "$@"
